"""Generate prisma/seed.ts from alpha-catalog.json using actual image slugs."""
from pathlib import Path
import json

meta = json.loads(Path(r"d:\Apollo\scripts\alpha-catalog.json").read_text(encoding="utf-8"))

lines = [
    'import "dotenv/config";',
    'import { PrismaClient } from "@prisma/client";',
    'import { hashPassword, isStrongAdminPassword } from "../src/lib/auth";',
    "",
    "const prisma = new PrismaClient();",
    "",
    "const products = [",
]

for p in meta:
    desc = p["description"].replace("\\", "\\\\").replace('"', '\\"')
    lines.append("  {")
    lines.append(f'    slug: "{p["slug"]}",')
    lines.append(f'    name: "{p["name"]}",')
    lines.append(f'    description: "{desc}",')
    lines.append(f'    price: {p["price"]},')
    lines.append(f'    featured: {"true" if p["featured"] else "false"},')
    lines.append(f'    category: "{p["category"]}",')
    lines.append("  },")

lines += [
    "];",
    "",
    "function productImage(slug: string) {",
    "  return `/products/${slug}.png`;",
    "}",
    "",
    "async function main() {",
    "  const keepSlugs = products.map((p) => p.slug);",
    "",
    "  await prisma.wishlistItem.deleteMany({",
    "    where: { product: { slug: { notIn: keepSlugs } } },",
    "  });",
    "",
    "  const removable = await prisma.product.findMany({",
    "    where: {",
    "      slug: { notIn: keepSlugs },",
    "      orderItems: { none: {} },",
    "    },",
    "    select: { id: true },",
    "  });",
    "  if (removable.length) {",
    "    await prisma.product.deleteMany({",
    "      where: { id: { in: removable.map((p) => p.id) } },",
    "    });",
    "  }",
    "",
    "  await prisma.product.updateMany({",
    "    where: { slug: { notIn: keepSlugs } },",
    "    data: { featured: false, inStock: false },",
    "  });",
    "",
    "  for (const product of products) {",
    "    const imageUrl = productImage(product.slug);",
    "    await prisma.product.upsert({",
    "      where: { slug: product.slug },",
    "      update: {",
    "        name: product.name,",
    "        description: product.description,",
    "        price: product.price,",
    "        featured: product.featured,",
    "        category: product.category,",
    "        imageUrl,",
    "        inStock: true,",
    "      },",
    "      create: {",
    "        slug: product.slug,",
    "        name: product.name,",
    "        description: product.description,",
    "        price: product.price,",
    "        featured: product.featured,",
    "        category: product.category,",
    "        imageUrl,",
    "        inStock: true,",
    "      },",
    "    });",
    "  }",
    "",
    "  console.log(`Seeded ${products.length} Alpha Polymers catalog products`);",
    "",
    "  const adminEmail = process.env.ADMIN_EMAIL?.trim().toLowerCase();",
    "  const adminPassword = process.env.ADMIN_PASSWORD;",
    "",
    "  if (!adminEmail || !adminPassword) {",
    '    throw new Error("ADMIN_EMAIL and ADMIN_PASSWORD must be set in backend/.env before seeding.");',
    "  }",
    "",
    "  if (!isStrongAdminPassword(adminPassword)) {",
    '    throw new Error("ADMIN_PASSWORD must be at least 12 characters and include uppercase, lowercase, a number, and a special character.");',
    "  }",
    "",
    "  const passwordHash = await hashPassword(adminPassword);",
    "  const existing = await prisma.user.findUnique({ where: { email: adminEmail } });",
    '  const resetPassword = process.env.SEED_RESET_ADMIN_PASSWORD === "true";',
    "",
    "  if (existing) {",
    "    await prisma.user.update({",
    "      where: { email: adminEmail },",
    "      data: {",
    '        role: "admin",',
    '        firstName: "Alpha",',
    '        lastName: "Admin",',
    "        ...(resetPassword ? { passwordHash } : {}),",
    "      },",
    "    });",
    "    console.log(",
    "      resetPassword",
    "        ? `Admin updated with new password: ${adminEmail}`",
    "        : `Admin ensured (password unchanged): ${adminEmail}`",
    "    );",
    "  } else {",
    "    await prisma.user.create({",
    "      data: {",
    "        email: adminEmail,",
    "        passwordHash,",
    '        firstName: "Alpha",',
    '        lastName: "Admin",',
    '        role: "admin",',
    "      },",
    "    });",
    "    console.log(`Admin created: ${adminEmail}`);",
    "  }",
    "}",
    "",
    "main()",
    "  .catch((e) => {",
    "    console.error(e);",
    "    process.exit(1);",
    "  })",
    "  .finally(async () => {",
    "    await prisma.$disconnect();",
    "  });",
    "",
]

Path(r"d:\Apollo\backend\prisma\seed.ts").write_text("\n".join(lines), encoding="utf-8")
print("seed.ts written", len(meta), "products")
